const W='https://api.open-meteo.com/v1/forecast', G='https://geocoding-api.open-meteo.com/v1/search', A='https://air-quality-api.open-meteo.com/v1/air-quality', E='https://api.open-meteo.com/v1/elevation', U='https://earthquake.usgs.gov/fdsnws/event/1/query';
const t=(u,ms=9000)=>Promise.race([fetch(u).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}),new Promise((_,r)=>setTimeout(()=>r(Error('timeout')),ms))]);
export const defaultLocation={name:'Dimapur, Nagaland, India',latitude:25.9091,longitude:93.7266,country:'India',admin1:'Nagaland'};
export async function searchLocation(q){const j=await t(`${G}?name=${encodeURIComponent(q)}&count=8&language=en&format=json`);return (j.results||[]).map(x=>({name:[x.name,x.admin1,x.country].filter(Boolean).join(', '),latitude:x.latitude,longitude:x.longitude,country:x.country,admin1:x.admin1}));}
export async function weather(loc){const p='temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,rain,showers,precipitation_probability,weather_code,cloud_cover,wind_speed_10m,wind_direction_10m,wind_gusts_10m,uv_index';const d='weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,rain_sum,precipitation_probability_max,sunrise,sunset,uv_index_max';return t(`${W}?latitude=${loc.latitude}&longitude=${loc.longitude}&current=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,rain,showers,weather_code,cloud_cover,wind_speed_10m,wind_direction_10m,wind_gusts_10m&hourly=${p}&daily=${d}&timezone=auto&forecast_days=7`)}
export async function air(loc){return t(`${A}?latitude=${loc.latitude}&longitude=${loc.longitude}&current=european_aqi,us_aqi,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,ozone&timezone=auto`).catch(e=>({error:e.message}))}
export async function elevation(loc){const j=await t(`${E}?latitude=${loc.latitude}&longitude=${loc.longitude}`).catch(e=>({error:e.message}));return {meters:j.elevation?.[0],error:j.error}}
export async function earthquakes(loc,radius=300){const end=new Date().toISOString();const start=new Date(Date.now()-7*864e5).toISOString();const j=await t(`${U}?format=geojson&starttime=${start}&endtime=${end}&latitude=${loc.latitude}&longitude=${loc.longitude}&maxradiuskm=${radius}&minmagnitude=2.5&orderby=time`).catch(e=>({error:e.message,features:[]}));return (j.features||[]).map(f=>({id:f.id,mag:f.properties.mag,place:f.properties.place,time:f.properties.time,alert:f.properties.alert,depth:f.geometry.coordinates[2],longitude:f.geometry.coordinates[0],latitude:f.geometry.coordinates[1],url:f.properties.url,distanceKm:dist(loc.latitude,loc.longitude,f.geometry.coordinates[1],f.geometry.coordinates[0])}));}
export const dist=(a,b,c,d)=>{const R=6371,rad=x=>x*Math.PI/180;let x=rad(c-a),y=rad(d-b);let h=Math.sin(x/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(y/2)**2;return Math.round(2*R*Math.asin(Math.sqrt(h)))};
export async function bundle(loc){const [w,aq,el,eq]=await Promise.allSettled([weather(loc),air(loc),elevation(loc),earthquakes(loc)]);return {weather:w.value||{error:w.reason?.message},air:aq.value||{},elevation:el.value||{},earthquakes:eq.value||[],updatedAt:new Date().toISOString()}}
export function nextRain(w){const h=w.hourly;if(!h)return null;const now=Date.now();for(let i=0;i<h.time.length;i++){if(new Date(h.time[i]).getTime()>now && ((h.precipitation_probability?.[i]||0)>=40||(h.rain?.[i]||0)>0.2||(h.precipitation?.[i]||0)>0.2))return {time:h.time[i],prob:h.precipitation_probability?.[i],rain:h.rain?.[i]||h.precipitation?.[i]};}return null}
